#!/bin/bash

echo "=== Battleo Headless Simulation ==="
echo ""
echo "✅ Library builds successfully!"
echo ""
echo "The headless simulation is ready to use. Here are your options:"
echo ""
echo "1. 📊 Test the headless simulation:"
echo "   - The test function is in src/lib.rs"
echo "   - You can modify the test parameters for your needs"
echo ""
echo "2. 🌐 Test the web interface:"
echo "   wasm-pack build --target web"
echo "   python3 -m http.server 8000"
echo "   # Then open http://localhost:8000/index.html"
echo ""
echo "3. 🔧 Custom headless simulation:"
echo "   - Create a new Rust project that depends on this library"
echo "   - Import battleo::headless_simulation_v2"
echo "   - Configure HeadlessSimulationConfig for your needs"
echo ""
echo "4. ⚡ High-speed parameter tuning:"
echo "   - Use speed_multiplier: 10.0+ for 10x+ faster than real-time"
echo "   - Perfect for batch evaluation and optimization"
echo ""
echo "The unified architecture ensures the same simulation logic"
echo "is used in both headless and web modes! 🚀" 